### ISSUE TITLE
Tickets page: Design Mockups

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#1002]
Based on content from https://github.com/mozilla/mozillafestival.org/issues/927

https://mozillafestival.org/tickets

Create revised design mockups to be approved before we implement it on the website.

**Comment by consuelamckenzie** [comment]
@sabrinang this is also another option for our many ticket options. It's also a very familiar format for those working with the web.

<img width="1193" alt="screen shot 2018-07-17 at 11 59 32" src="https://user-images.githubusercontent.com/40797384/42813505-28f43666-89b9-11e8-9187-8aa42d5c1877.png">

**Comment by sabrinang** [comment]
**Option 1 - Ticket Mockup (full-width list style)** 

redpen: https://redpen.io/qs553c471f084f1706

**Option 2 - Ticket Mockup (compare card style)** 
Copy should be rewritten so tickets points are easily comparable to one another and I changed the order and added heading suggestions (example: weekend, day, full festival) to help readers scan the ticket types.

redpen: https://redpen.io/ug7a9e6dc9b6fe7083

**Comment by sabrinang** [comment]
Redpen updated: https://redpen.io/ug7a9e6dc9b6fe7083
- points have been relocated above the button in order for buttons to align on the bottom

**Comment by zee-moz** [comment]
hi @sabrinang  Thanks for this! 
I see what you mean about the bullet points. From what I can tell, we have three (or four?) ticket types that are identical-- the weekend, benefactor, and champion are basically the same, with the same bullet points, but different pricing that attendees can select to express their support for the Festival and the mission. I THINK the youth ticket is also the same, except the kids don't get Saturday night party access?  IS that right  @marcwalsh? Everyone gets swag, and hands on experience with the latest tech, etc. 

To avoid having people read and compare across basically identical bullet lists on each ticket type, how about a paragraph at the top, that says: "Unless otherwise noted, all Weekend tickets include: " ... then have the bullet points. 

Then each ticket type listed, a short description about why you'd chose that one, with a disclaimer on the youth type that says: "Does not include evening party."  @marcwalsh @caltrider @consuelamckenzie what do you think?

**Comment by sabrinang** [comment]
@Saallen Redpen updated: https://redpen.io/ug7a9e6dc9b6fe7083 according to https://github.com/mozilla/mozillafestival.org/issues/927#issuecomment-407192046 and moved italicized text below button according to @consuelamckenzie feedback

**Comment by sabrinang** [comment]
@Saallen Redpen updated: https://redpen.io/ug7a9e6dc9b6fe7083 according to https://github.com/mozilla/mozillafestival.org/issues/927#issuecomment-407423810 and left some questions on [google doc](https://docs.google.com/document/d/1Yz0xET9I5fji9MFEt3ri0YC4vdRQesKZkt2YzjgxGis/edit#)

**Comment by sabrinang** [comment]
Redpen updated: https://redpen.io/ug7a9e6dc9b6fe7083 
- all asterisks are bullet points
- full stops removed from italicized text under button
________________________
Design review approval?
- [ ] @Saallen

**Comment by Saallen** [comment]
approved and looks great-

**Comment by sabrinang** [comment]
Final copy updated from #927 on [redpen mockup](https://redpen.io/ug7a9e6dc9b6fe7083). Closing ticket and dev work will be tracked on implementation ticket https://github.com/mozilla/mozillafestival.org/issues/926
