### ISSUE TITLE
QA: Website Footer

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#1010]
Capturing @consuelamckenzie's footer feedback as QA issue
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/2492510/43107071-39d39266-8e90-11e8-9c64-0fff6405badf.png">
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/2492510/43107089-4a59dd34-8e90-11e8-91d4-a0938b7b299e.png">

For footer language, we will have to coordinate across all MoFo properties for any changes. 

Will we be using instagram for MozFest? If so which handle is appropriate to link too and is this something we need to coordinate across our other properties?

Example: reference https://foundation.mozilla.org/ footer if we want to include links such as donate

**Comment by consuelamckenzie** [comment]
@sabrinang for Instagram, after team "Mozfest feedback, there is not an existing Mozfest Instagram account and we are not setting one up for the festival. It seems Mozilla's Instagram account is the main account we would use and this shouldn't feature on the Mozfest site.
For the footer text used across Mozilla sites, it should read "...the future of the web for public good." The second "the" is the one that we need to loose if a typo.

**Comment by gideonthomas** [comment]
Hi @consuelamckenzie, the copy for that footer has been provided by our Mozilla communications team to be used on all of our websites (e.g. we use it in our main [Mozilla Foundation site](https://foundation.mozilla.org/) as well). As such, it doesn't seem like it's a typo in the text and the second "the" is intentional. 

As Matthew Willse mentions, if you would like to propose this change so that it applies to all our Mozilla websites, I can put you in touch with our communications team.

If you're ok with this, feel free to close this issue, otherwise, I'm happy to chat further about the copy.

**Comment by consuelamckenzie** [comment]
Hi @gideonthomas, If the footer copy is being used across Mozilla websites and the copy is approved there seems little point in changing this. Closing this issue.
