### ISSUE TITLE
Spaces page: Experience Description for Gaming MozFest

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#1021]
We need a Gaming MozFest experience description submitted to appear on our spaces page. These descriptions will be reviewed to go on the Spaces page under the _2018 Experiences_ section.

Other space/experience descriptions can be referenced here https://github.com/mozilla/mozillafestival.org/issues/850#issuecomment-390704087

**Comment by Saallen** [comment]
Still waiting on the description

**Comment by Saallen** [comment]
Gaming MozFest experience-
Every day, many of us are pressured into offering up pieces of personal data in order to participate on the internet. To sign up for a social network we need to provide our full name. To download a gaming app we need to provide access to our phone’s contact list. What kinds of trade-offs do we make when we hand over that data? What are we really getting in exchange? How can consent exist in this system? Tracked is a large-scale game designed for MozFest 2018 centered on the festival theme of “Your Data and You.” The game will engage players in various activities throughout the festival space, demonstrating the various trade-offs we each make when it comes to our data. As participants are encouraged to quantify, document, and report on various pieces of information throughout the game, the hope is that they will also reflect on the choices we are constantly making about our data.


Approved already by kevin and myself. Gideon, this is ready for website
cc @zee-moz  for ref
