### ISSUE TITLE
Fringe event page

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#1065]
@sabrinang @mmmavis 
The fringe event page is updated and the URL live -but not accessible from the website.
Can you remove tweet mozfest from the bottom nav bar and have fringe page here instead?

**Comment by mmmavis** [comment]
Sure. What icon should we use for that fringe page link on footer? @sabrinang (fyi we have font awesome v4 linked to our site)

**Comment by gideonthomas** [comment]
Will assign to dev once we have an icon for the fringe link in the footer. This will replace the "Tweet MozFest" footer element.

**Comment by gideonthomas** [comment]
Awesome, thanks @sabrinang.

Assigning to @mmmavis to use the `fa-calendar` icon to link to the fringe events page. This will replace the "Tweet Mozfest" item in the bottom navigation.

**Comment by Saallen** [comment]
I think the calendar icon looks a little confusing and I would expect to see the schedule here

**Comment by sabrinang** [comment]
@Saallen Would you prefer a list icon instead of a calendar to represent a schedule better?
![image](https://user-images.githubusercontent.com/2492510/44356922-8ed86a80-a465-11e8-9076-95411a4b0d17.png)

I just assumed there would be an event listing or calendar since [the page](https://mozillafestival.org/fringe) includes the line "_Add your event to the MozFest Fringe calendar_"

**Comment by mmmavis** [comment]
Live: https://mozillafestival.org/ 'Fringe' has been added to nav bar.
