### ISSUE TITLE
Sponsorship webpage update request

### ISSUE THREAD

**Issue by consuelamckenzie** [mozilla/mozillafestival.org#1080]
Can you please add on our website sponsor page this click through link on the Sticker Mule logo; https://mule.to/mozfest-2018?

Thanks
Consuela

**Comment by gideonthomas** [comment]
Hi @consuelamckenzie, is that link supposed to end up on https://www.stickermule.com/uses/hexagon-stickers?utm_source=MozFest-2018&utm_campaign=MozFest-2018-sponsorship&utm_medium=referral? Or is it supposed to redirect to the main sticker mule page?

Also, just want to clarify that this link is intentional...none of the other sponsors on the sponsor page links to any website, sticker mule will be the only one - is that correct?

cc @Saallen

**Comment by gideonthomas** [comment]
Also, @consuelamckenzie, can you comment in https://github.com/mozilla/mozillafestival.org/issues/1027 with a list of sponsors and links (whatever you have so far, including this one to stickermule)? Ideally we track all the sponsorship data in that ticket.
