### ISSUE TITLE
Design new section for blogs/news

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#502]
For [MozFest landing page](https://mozillafestival.org/)

Follow MLN site design for a blog/news section fed from:
- our Medium blog
- other people's Medium blogs
- news

'View More News' button can link to our Medium: https://medium.com/mozilla-festival

This section should go under the Speakers

**Comment by sabrinang** [comment]
Mockup of blog post section with content from medium and using sites typographic styles: ![mozilla-festival_update-0217-02](https://cloud.githubusercontent.com/assets/2492510/22971424/7ae43290-f32a-11e6-8b3a-39b5d7b85678.png)

**Comment by edrushka** [comment]
👍 Would this section have a different background colour?

**Comment by sabrinang** [comment]
No, I don’t think a background colour is necessary and we can keep the white space but we can swap the grey seen on the bottom to the to divide this section (and remove horizontal line under title) since it doesn’t seem like the grey is limited to any particular usage. This grey would work but any colour bg would be too busy for this section and colour bg isn't used else where on the site.
<img width="1257" alt="alternative-divider" src="https://cloud.githubusercontent.com/assets/2492510/22988724/f625f078-f367-11e6-8775-8a249955cad1.png">

**Comment by edrushka** [comment]
Grey is perfect, and I like the removal of the line under the title. Thanks!

**Comment by hannahkane** [comment]
Awesome. @sabrinang - would you mind filing an implementation ticket with whatever assets a dev would need (if any)?

**Comment by hannahkane** [comment]
Actually, realizing a significant part of the implementation is figuring out how we're going to pull in content, so don't worry about filing that ticket, @sabrinang; I can do it. But can you confirm that there are no new assets needed to implement this design? Thanks!

**Comment by edrushka** [comment]
Implementation is included in ticket #503

**Comment by sabrinang** [comment]
It uses all existing colours and typography of the site, the only additional asset is using Medium's logo icon above the titles which can be downloaded here: https://github.com/Medium/medium-logos/archive/master.zip

**Comment by alanmoo** [comment]
Unless I'm missing something, the typographic styles used aren't readily available to components outside the ones they're used in. In the future I'd like to unify the typography with the rest of MoFo Bootstrap but that's not going to be possible before tomorrow. So after this lands, there may need to be some massaging of the typography, but I'll make it look reasonably good at least.
