### ISSUE TITLE
Propose a Proposal Curation Flow for 2017

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozillafestival.org#538]
### What we used last year

- flowchart: https://www.lucidchart.com/documents/view/822b0b42-6486-409f-a465-c6834ae56276
- system/platform involved
  - MozFest site: http://mozillafestival.org/
  - Google Form: (a copy of the real form) https://docs.google.com/a/mozillafoundation.org/forms/d/1yKv9mRzkGcq3bCDCDEUbI8e4gVRPGHNebYHeV2fk8cg/edit
  - multiple Google Spreadsheets
  - GitHub repo: https://github.com/MozillaFoundation/mozfest-program-2016/issues
  - other tools that wranglers use on their end (I'm not sure how wranglers curate proposals)

### This year+

Let's brainstorm some ideas to make our existing flow smoother.

/cc @simonwex @kristinashu

**Comment by kristinashu** [comment]
Are there any requirements for the new flow? Was the purpose of GitHub so that anyone could view, comment on and edit a session proposal?

Any idea how wrangles felt about using GitHub for this (was it easy enough for them to use, did it do everything they needed...)?

**Comment by mmmavis** [comment]
> Are there any requirements for the new flow?

For requirements
1. we must make the curation process open and transparent to public
2. form needs to allow custom questions

We don't have the resources to build a curation platform ourselves that's why we will likely continue using Google Form and GitHub (suggestions welcome!)

>  Was the purpose of GitHub so that anyone could view, comment on and edit a session proposal?

Yes to view and comment. Not so sure about editing a session proposal. For dev perspective I'd like us to find a way to restrict people from editing proposal in GitHub (as any changes can easily break the markdown format that the parsing script understands). Would love to hear what @edrushka @Saallen think from program people perspective.

> Any idea how wrangles felt about using GitHub for this (was it easy enough for them to use, did it do everything they needed...)?

@edrushka @Saallen could you comment on this one? 😉

**Comment by edrushka** [comment]
We want to encourage discussion and adjustments to sessions in the Github _comments_ (versus editing the initial, auto-generated comment) because, as Mavis pointed out, if people break the markdown it will mess up the script for the schedule.

I think wranglers had varying degrees of comfort with using Github. Areas of confusion didn't stem from the Github platform, but rather from how we were using it. Two of the biggest areas of confusion were:
- when wranglers removed their space labels, leaving the issue homeless in the repo, and
- when wranglers tried to use labels or comments to send the issue to another space. This got messy and sometimes confused the new space's curation system.

This year, it would be great if we could improve that hand-off process, when one space doesn't want a session but thinks it will fit well somewhere else.

We will use MozRetreat in Tallinn as an opportunity to get more specific feedback and suggestions from the wranglers.

**Comment by Saallen** [comment]
The beauty of guthub is 
*transparency- between submissions, between wranglers and gen public
* visual movement of the curation process- labelling and milestones are super important visual filters and markers for the process. Wranglers pick and choose how to curate themselves, so some download their submissions via google sheet, others write them all out on cards. Then they go back to github and are supposed to remove the label from issues they are not accepting- this worked well for 90% of the spaces.
Where we saw issues, is when ppl added other space labels trying to cross share an issue/session- this lead to confusion on ownership

I can upload last years versus 2015 working processes later- 
+1 to erikas comment

* If we are using a different scheduling system this year will this allow for a more fluid system and allow for sessions direct to github?

**Comment by Saallen** [comment]
@mmmavis 
Here are the processes for ease of understanding from [2015](https://github.com/mozilla/mozfest-program) and 2016

In 2015 
*Issues were submissions/session proposals
*Milestones represented Spaces
*Labels represented pathways- many labels could be applied to issues

In 2016 - we swapped things around a little
*Issues were submissions/session proposals
* Milestones were markers of the curation process Under consideration or Accepted- 
* Labels represented spaces- only one label per session- no label meant the session was not being accepted as part of the programic
