### ISSUE TITLE
No content when landing with JavaScript disabled

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#565]
I received a tweet complaining about the website.
I asked Cade and he thinks "That's NoScript - an add-on that disabled JavaScript. The MozFest site probably needs JS to display properly" 

@mavis How should I respond to our friend below?
![screen shot 2017-05-22 at 16 48 19](https://cloud.githubusercontent.com/assets/10194015/26318762/1cc7018e-3f14-11e7-9f62-ea161663f1ae.png)

**Comment by Pomax** [comment]
This is a valid complaint, no site should break because analytics is blocked, so "good catch! It looks like the code was missing namespace validation, we'll fix that asap, thanks for letting us know!" is a good response, and we need to make sure all our `ga` events are wrapped by a check to make sure analytics is available:
```
if (window.ga) { 
  ga.event(...);
}
```

**Comment by Saallen** [comment]
Thanks @Pomax appreciate the help :rescue_worker_helmet:

**Comment by mmmavis** [comment]
Reopen - we need to make sure our GA respect user's DNT setting. I will submit a PR.

**Comment by Pomax** [comment]
Reclosed - DNT is a different issue, not still this one.
