### ISSUE TITLE
Add sponsors to sponsor page

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#761]
@mmmavis I have emailed you all the sponsor logos. Please add them to https://mozillafestival.org/team/sponsors underneath the paragraph text. If it needs header text you can put Our 2017 Sponsors.

**Comment by mmmavis** [comment]
@edrushka I heard from @sabrinang that we are still finalizing the types of sponsorship as well as which type each sponsor belong to. Can you paste the finalized list here when they are ready? Thanks!

**Comment by edrushka** [comment]
We are ready. Ordering for tiering them is [here](https://docs.google.com/document/d/1unimp4LxiOa2tLOEUAFmWlLFktuNzoRYwUc9Sh_-Y_g/edit). I emailed you all the logos.

**Comment by mmmavis** [comment]
I will work on this ticket today.

**Comment by mmmavis** [comment]
@edrushka do we want the logos to be hyperlinked? If so, could you please provide the links (you can add them in google doc or here). Thanks!

**Comment by mmmavis** [comment]
@edrushka I exported the provided logos into PNGs without cropping off the any whitespace as I don't know if that'll violate their brand guides. I can't seem to layout logos nicely because of the sizes of the logos vary a lot (see red boxes below). Should we consider a different layout than what's suggested in this [doc](https://docs.google.com/document/d/1unimp4LxiOa2tLOEUAFmWlLFktuNzoRYwUc9Sh_-Y_g/edit?ts=59deb21a)?  

![screen shot 2017-10-16 at 18 31 29-fullpage](https://user-images.githubusercontent.com/2896608/31642518-48cb65a4-b2a0-11e7-8697-dbc767137a2f.png)

**Comment by edrushka** [comment]
cc @jcbarajas how does this layout look to you (minus the red boxes)? Should we link out to each of the sponsors' main websites?

**Comment by jcbarajas** [comment]
Looks great! We probably can just say partner vs partners since it's only one per category.

Also, let's say Supporting Festival Partner on top of Flattr's logo.

**Comment by mmmavis** [comment]
Just wanted to get this page out soon so here it is https://mozillafestival.org/team/sponsors 🎉 

I adjusted spacing and header colour a bit. If there's any tweaks I can make just let me know! :)
