### ISSUE TITLE
New banner image for House page

### ISSUE THREAD

**Issue by edrushka** [mozilla/mozillafestival.org#820]
@sabrinang do you have a horizontal version of this pic (or something equally nice) that we could turn into a hero banner image on https://mozillafestival.org/house?

I found this image in https://github.com/MozillaFoundation/mozfest-design-2017/issues/69

![32971637-f308fd2c-cba2-11e7-94ea-2f2994b9b49f](https://user-images.githubusercontent.com/4515662/36056229-78b5dade-0db7-11e8-8f84-c68d78b23570.jpg)

**Comment by sabrinang** [comment]
@edrushka No, I didn't take a horizontal version of that image sadly. We can try cropping it to make it work or try other horizontal photos:
https://drive.google.com/file/d/1tPo2afmCHFdE-12VzbqPTXx9NQVTqJSS/view?usp=sharing
https://drive.google.com/file/d/11zg9Frbwf8OiM7jv_pMEWLZ8uH2Ydj0Y/view?usp=sharing

All house photos I shot were mainly documenting assets though but you can find them in this drive folder: https://drive.google.com/open?id=1mgBSTjC4jHoVEL9urCKMf3kktmE9a9wt

**Comment by edrushka** [comment]
If you have a moment @sabrinang could you try cropping that one? The people and the flower pattern on the ceiling make it feel quite lively. If it doesn't work, we can go with [this one](https://drive.google.com/file/d/11zg9Frbwf8OiM7jv_pMEWLZ8uH2Ydj0Y/view?usp=sharing).

**Comment by sabrinang** [comment]
Here is a cropped version of it:
![mozfest-house-40-cropped](https://user-images.githubusercontent.com/2492510/36503510-36a25646-1702-11e8-9539-2122f2339d71.jpg)

Since this seems to be for the hero banner, I treated it with colour as well in case you are putting text in front of it:
![mozilla-festival-house_banner-2018 2x](https://user-images.githubusercontent.com/2492510/36503431-f3a06b94-1701-11e8-980c-03ba1799da55.jpg)

These can be found with the rest of the of the website assets on gdrive here: https://drive.google.com/open?id=1IoNCm9UYn1iFoAsCA3cvORiN6GXzDtUG

**Comment by ScottDowne** [comment]
I think this is done on staging: https://mozillafestival-org-staging.herokuapp.com/house
