### ISSUE TITLE
CFP Form: Write Call for Proposal Form

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#863]
This form will be used on https://mozillafestival.org/proposals

- [x] decide l10n requirements
- [x] write set of questions and design question types _(short answer, multiple choice etc)_
- [x] decide what labels, milestones, etc we wanna auto-apply to proposals(GitHub tickets) in our 2018 proposal GitHub repo

**Comment by sabrinang** [comment]
**Update:** We decided to keep the call for proposal form in English only but to include an option in the form to submit a proposal in their language and to indicate the language.

**Timeline:**
May 3 - Draft CFP questions complete
May 16 - Space narratives complete
May 21 - Form copy and design finalized to hand-off to Mavis

**Comment by Saallen** [comment]
Making an extension to May 8th for first draft of CFP 🌸

**Comment by Saallen** [comment]
Draft complete- here are the proposed questions


**Section 1**

- first name* [short text field]
- surname* [short text field]
- Organisation [short text field]
-  Twitter [short text field]
- Github [short text field]
- Additional facilitator 1 First name
- Additional facilitator 1 surname
- Additional facilitator 1 email
- Additional facilitator 1 github
_[click for additional facilitators]_
    Additional facilitator 2 name
    Additional facilitator 2 surname
    Additional facilitator email
    Additional facilitator github

All sessions must be submitted in a Space. Read about each space here.* [insert link to spaces]
- What Space do feel your session will best contribute to?* [dropdown menu]

**Section 2**
MozFest will be hosted with English as the principle language  and the majority of participants will speak english as first or second language.
However if you wish to lead your session in another language or support your session in multiple languages, please let us know. We know from previous years we have substancial numbers of Spanish, German and French speakers
- Do you wish to propose or faciliate your session in another language?[checkbox]
- Yes 
- No
- Maybe

_If No_ Straight to section 4
If yes/maybe connect to section 3

**Section 3**
MozFest can provide some support for sessions in other languages  Please note we may not be able to support all of your needs but will work with you to provide the best solution possible.
- Will you need additional support from MozFest to deliver this session on the day [check box]
-     Yes- to help translate the session on the day as I will host in another language, and am unable to facilitate in English
-     No- I will host myself or bring additional support onsite, such as printed materials etc
-     Other, please explain

What language will you delivery your session in
- Spanish
-     French
-     Italian
-   Hindi
-     Bengali
-     German
-     Russian
-     Greek
-     Portugese
-     Mandarian
-     Other---please just write language
-     English// No I have changed my mind

**Section 4**
Describe how your session or activity allow people to make, learn or do
- What is the name of your session?
-     What will happen in your session?* [short paragraph] word limit 120
-     What is the goal or outcome of your session?*[paragraph]word limit 120
-     After the festival, how will you and your participants take the learning and activities forward?word limit 120
-     How will you deal with varying numbers of participants in your session? What if 30 participants attend? What if there are 3?*

Session formats--We have created 3 session formats so that 
1. we can understand what type of proposal you will deliver
2.  understand how you see the participants interacting with your session
Choose one format that most suits how you want
-  Learning Forum session-Sessions here develop and implement ideas for improvement, exchange or review. 
-  Gallery session- this session is an interactive exhibit, installations, a game, a stalls- designed for 1:1 self driven experience or small group activities. Often these experiences or activities are not scheduled time blocks but take place over the day or weekend allowing access and interaction at any time
-   Shed session- this session requires hands-on making, hacking and prototyping. Session will ask participants to create and build code, objects or crafts.
How much time you will need.
-  less than 60 mins 
-     60 mins
-     90 mins
-     all weekend/ongoing

**Additional support**
Many attendees bring a personal device (smartphone, laptop or tablet) to the festival. We can provide you with a projector, and office supplies (paper, pens, post-it notes). If your session requires additional materials or electronic equipment, please outline your needs below. Please note we may not be able to support all of your needs but will work with you to provide the best solution possible. - parapraph

 MozFest has a limited number of travel stipends to help those who otherwise would not be able to attend. We offer these stipends to increase diversity at the festival as well as to assist those who:
1. are unemployed or a student with limited means
2. have no other means of covering costs, such as personal finances or through work
Do you identify yourself in one of the above categories?
-     Yes
-     No

**Submitt**

**Comment by Saallen** [comment]
Last day for feedback @KevZawacki @kgorr @amirad and Amanda

@caltrider can you review the top message of the form in particular and let me know what you think

**Comment by KevZawacki** [comment]
Hi @Saallen, I caught two small typos. Update text below, with changes **bolded**: 

Anyone may submit a proposal for MozFest 2018. Once you have submitted your session, it will enter an open curation process on Github, and all information **you** submit here [insertlink later], apart from email and **T**witter handle will be seen **publicly**. We will contact all submissions via Github by default, and email afterwards.

...

If you would like to submit your session in another language there are ways **to do so below**. If you have difficulty submitting via texted based form please reach out to us to discuss other accessibility options.

**Comment by amirad** [comment]
@Saallen Working on revisions here 

https://docs.google.com/document/d/1G_f3hzggiIx0sZZRH9uzpGqJ1RjjunIDhRIMxP9fgGk/edit

**Comment by caltrider** [comment]
@Saallen Gave it a close read. I think it looks good. A couple of thoughts for consideration.

1. Is there one short sentence that outlines the goals of a Mozfest session?  Something like "The goal of every session at Mozfest is to find ways to make life on the internet better." That could help set the tone for people pitching sessions.  

2. It's mentioned all sessions should be "interactive and inclusive". It might be nice to define very simply what that means. Interactive is a little more obvious, inclusive is one of those words that can get over-used and perhaps lose a bit of meaning. Defining these super simply in a couple words (ie. Interactive = everyone can get involved in the session if they want, inclusive = fun and respectful for everyone who attends) could help set the tone for what you're looking for in sessions.

My thoughts, otherwise, I think it looks good.

**Comment by amirad** [comment]
Yes and Yes, esp that number 2 that @caltrider suggested

**Comment by amirad** [comment]
Adding @zee-moz who has some great feedback for the proposal form!

**Comment by amirad** [comment]
Thanks @Saallen - any way we can continue to have stronger language in the stipend part while adjusting the language? Or at least change the line "Do you qualify as such?" to "Do you require a stipend?"

**Comment by Saallen** [comment]
Hi @amirad this is the intensional ask "do you qualify" as everyone requires/wants a stipend. It becomes really hard for wranglers to ask over 400 submissions (last years response rate to do you require a stipend) if they really need the stipend or can work/personal funds cover.

**Comment by mmmavis** [comment]
Thanks for providing and consolidating feedback.  Form has been implemented and should be ready for QA Monday next week.

Regarding the last todo on this ticket: 

> decide what labels, milestones, etc we wanna auto-apply to proposals(GitHub tickets) in our 2018 proposal GitHub repo

Here is the list of milestones and labels we decided to auto apply to proposal tickets on GitHub:

## Milestone

(a proposal's primary space choice) (a ticket can only have max of 1 milestone applied)

1. `Decentralization`
2. `Digital Inclusion`
3. `Openness`
4. `Privacy and Security`
5. `Web Literacy`
6. `Youth Zone`
7. `Queering MozFest`

## Labels

(a ticket can have multiple labels)

### Session Format

1. `[Format] Learning Forum`
2. `[Format] Shed`
3. `[Format] Gallery`

### Secondary Space

1. `[Secondary Space] Decentralization`
2. `[Secondary Space] Digital Inclusion`
3. `[Secondary Space] Openness`
4. `[Secondary Space] Privacy and Security`
5. `[Secondary Space] Web Literacy`
6. `[Secondary Space] Youth Zone`

### Localisation related

1. `Localisation support requested`
2. `[LANG] Spanish`
3. `[LANG] French`
4. `[LANG] Italian`
5. `[LANG] Hindi`
6. `[LANG] Bengali`
7. `[LANG] German`
8. `[LANG] Russian`
9. `[LANG] Greek`
10. `[LANG] Portugese`
11. `[LANG] Mandarin`
12. `[LANG] Other`

### Stipend related

1. `Stipend requested`

**Comment by mmmavis** [comment]
All todos completed! 🎉
