### ISSUE TITLE
CFP Form: Legal Review for Proposal Form

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#864]
The form text from https://github.com/mozilla/mozillafestival.org/issues/863 will be used on https://mozillafestival.org/proposals

- [ ] submit for legal review _(GDPR checkbox? etc.)_

**Comment by sabrinang** [comment]
@Saallen This ticket might be related to the legal, privacy, terms issue you wanted to file but this is specifically for the form.

**Comment by Saallen** [comment]
@sabrinang 
@jessevondoom thinks we are fine with our Google form but adding him here to confirm.

**Comment by jessevondoom** [comment]
Yeah I think we're good. The email address covers us for any kind of data removal request. 

Only suggestion would be working in a link to our community participation guidelines and our general privacy statement.

- https://www.mozilla.org/en-US/privacy/websites/
- https://www.mozilla.org/en-US/about/governance/policies/participation/

Something like "All proposed sessions must meet the standards of our community participation guidelines. Submissions are subject to the Mozilla privacy policy. If you have any questions..."

**Comment by mmmavis** [comment]
@jessevondoom @Saallen - just wanna bring it up that we will be creating a form on MozFest site and using Google "API" to send data over instead of directly using a Google Form (see [last year's example](https://user-images.githubusercontent.com/2896608/39336759-0db0e132-496e-11e8-9dfe-38b3106d74e5.jpg)). But I don't think this affects what has been mentioned above since data still gets stored on Google Sheet anyway.

@jessevondoom do we need to do something specifically for GDPR?

**Comment by Saallen** [comment]
I spoke with Legal and @stephaniemcv 
We do not need to do anything for google docs for GDPR in this instance
We are all good on gathering the information but we are ensuring that what we store and how is still uptodate and safe

**Comment by Saallen** [comment]
@mmmavis I email legal and waiting on a response

**Comment by Saallen** [comment]
Legal reviewed and agreed- nothing to change except the year from 2017- 2018

cc @mmmavis @sabrinang

**Comment by mmmavis** [comment]
Awesome. In that case I think we are good! Staging link: http://mozillafestival-org-staging.herokuapp.com/proposals (page header says 2018)

🎉 🎉 🎉 🎉 🎉
