### ISSUE TITLE
CFP Social: Localise Call for Proposals tweets

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#902]
Based on content in issue https://github.com/mozilla/mozillafestival.org/issues/859

We are requesting tweets to be localised in 5 languages (French, Spanish, German, Hindu, Swahili).

/cc @Saallen

**Comment by TheoChevalier** [comment]
Looks like the tweets here are still in review? https://docs.google.com/document/d/16Jz2_o0kGl5ECb9i25-5NIAkdH9JsRcC8yBhBkZJG4E/edit

Also heads up that some of them seem quite long and close to the character limit. It’s best if they can be shortened a little bit, but otherwise localizers will reformulate/drop some parts in order to fit.

**Comment by Saallen** [comment]
Hey @KevZawacki are you good to go with those tweets?

**Comment by KevZawacki** [comment]
@Saallen @TheoChevalier Good to go! 👍

**Comment by TheoChevalier** [comment]
Just to clarify here, after discussing with @KGorr, we noticed tweets were duplicates with the ones in the cheat sheet, so I went ahead and exposed the ones from the cheat sheet (also because they are shorter)

**Comment by sabrinang** [comment]
work is captured in l10n cheat sheet ticket here https://github.com/mozilla/mozillafestival.org/issues/903 since tweets were duplicated there - closing ticket
