### ISSUE TITLE
QA - call for proposal page

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#911]
@mmmavis the links on the top paragraph link to
* the old repo set up earlier in the year
* last years space page

can you please amend?

**Comment by mmmavis** [comment]
@Saallen github repo link seems to be correct to me on [staging](http://mozillafestival-org-staging.herokuapp.com/proposals). It links out to https://github.com/MozillaFestival/mozfest-program-2018

> last years space page

this won't be an issue after we push things live to mozillafestival.org since mozillafestival.org/spaces will then correctly displays this year's description

**Comment by Saallen** [comment]
awesome- thanks 👍 
👓
