### ISSUE TITLE
QA- automated email for submitted sessions

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#912]
Hey @mmmavis 
it seems that only the primary facilitator received the automated email- I think it would be good for all additional facilitators to receive the same automated email... is this possible?

**Comment by mmmavis** [comment]
@Saallen it should be technically possible but it'll take a few days to make that happen

Things we need to consider and do

- have a different version of email since the additional facilitators might not be aware someone has included them in a MozFest proposal (we don't want this email to look like spam/scam!)
- file devops tickets and get this new email working in the system
- update mozfest site's code so we can send the right version of email to the right people

**Comment by Saallen** [comment]
OOOHHHH -- this one is an issue
_have a different version of email since the additional facilitators might not be aware someone has included them in a MozFest proposal (we don't want this email to look like spam/scam!)_

Yes good catch it would need to say XXX submitted a session to MozFest with you as the second facilitator....

**Comment by mmmavis** [comment]
I've labelled this ticket with `Ideas for 2019` .

We don't have the capacity to do this this year. I'm closing this ticket now.
