### ISSUE TITLE
Production page: Add Production Coordinator Bio

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#938]
The Senior Production Coordinator will start in the upcoming months. Add their bio to the page.

**Comment by sabrinang** [comment]
@marcwalsh Please provide a short bio and photo for this page https://mozillafestival.org/team

**Comment by marcwalsh** [comment]
Hey @sabrinang!

Details below...

Bio:
`Marc is the Senior Production Coordinator for MozFest 2018, with this year being his seventh time working on the festival. Since last year he’s worked on large scale events around the world with organisations such as FIFA, BBC and BMW. Drawing on this experience, he brings his logistical and production mind-set to help make sure the cogs keep turning across the festival.`

Image:
![28615393-c6a6ed4a-71f0-11e7-903a-ca97fe8838e7](https://user-images.githubusercontent.com/30226684/42449407-7a406cca-8378-11e8-9258-13fbb74d5fdf.jpg)

**Comment by sabrinang** [comment]
@KevZawacki Can you please review this bio?

**Comment by KevZawacki** [comment]
@sabrinang Here it is with just a couple style tweaks:

Marc is the senior production coordinator for MozFest 2018, with this being his seventh year working on the festival. Since last year, Mark has worked on large scale events around the world with organisations such as FIFA, BBC and BMW. Drawing on this experience, he brings his logistical and production mind-set to help make sure the cogs keep turning across the festival.

**Comment by sabrinang** [comment]
Thanks @KevZawacki 👍
