### ISSUE TITLE
Fringe page: Copy

### ISSUE THREAD

**Issue by sabrinang** [mozilla/mozillafestival.org#947]
https://mozillafestival.org/fringe

Update the fringe page text.

**Comment by Saallen** [comment]
@caltrider and myself to meet about copy for this page

**Comment by Saallen** [comment]
MozFest is not only in London....

MozFest is about working in the open and sharing ideas with a global network of people dedicating to protecting the health of the Internet. This year’s festival theme is ‘Data and You’  and so we’re looking to champion events themed on data as we are asking our own MozFest audience to ask themselves questions such as What does the future of personal data and the internet as a global public resource look like a year from now? Five years from now? Ten years from now?

If your event demonstrates some of the following characteristics, we’d love to promote it as a MozFest Fringe event, and share some of our resources with you:

    Theme of the event focues on onestage of the life cycle of data, from collection, storage to use
    Event is co-designed with partners.
    Includes creative, hands-on activities.
    Facilitation promotes collaboration, innovation and respect.
    Designed in the open (e.g. you publish process blogs or have an open curation process).
    Presents leadership opportunities for all (attendees, mentors, event staff).
    Protects or advances the health of the Internet.
    Includes a code of conduct, ensuring all are welcome to share and be heard.

Add your event to the MozFest Fringe calendar.

**Comment by Saallen** [comment]
@zee-moz and @caltrider would love your input on copy for the fringe event page

Page purpose- to allow partners, friends and allies to promote their own Mozilla like event that takes place across the globe in a mozfest like format and ties into our theme data and you

Last years page here **https://mozillafestival.org/fringe**

**Comment by zee-moz** [comment]
@Saallen how many fringe events registered last year? trying to understand if current copy was effective in getting event sign-ups. 

my guess is that this page will be more effective if we provide more info about the value exchange associated with listing-- like what specifically what materials do we offer them, how do they get access, how does promotion as a fringe event benefit them?  Is there a % increase in attendance for fringe listed events? do we have testimonials from those running fringe events on how it went? how many page views of the calendar?  etc. Otherwise it seems more like a checklist of requirements, and not enough to encourage people to list their event. 

Also, some people may have an event with 6 of 8 bullet points checked-- can they add their event and use our materials to level up? 

Can we specifically offer OL6 application process, or OL101 as training opportunities here? 

In future, if we were so inclined, we could offer some kind of "event planning kit" -- could use for WOW,  Global Sprint-- that streamlines content from GS host site, WOW planning materials, and OLTS events module. This would be a great use of that material.

**Comment by Saallen** [comment]
Hi @zee-moz thanks for the feedback- fringe events are meant to be very low touch from us. 

Fringe events emerged from the network wanted to connect their events to the festival. 
We ultimately want to promote events that are taking place that are build in a similar strand to mozfest. (open, collaborative and this year themed around data) 

Last year we had 17 events submit and show up on the page

**Comment by marcwalsh** [comment]
@zee-moz, 

Just adding to Sarah's comment - we don't really offer that much in terms of support. The Fringe page is just meant to gain that extra piece of marketing for smaller events and possible allow people who are travelling to extend their MozFest experience a little longer.

We don't officially endorce the events as we do not have control over their content or how the event is run in terms of useing our materials etc, but have provided pieces like the festival guide to one or two events in the past.

I do like the idea of an 'event planning kit' that helps people plan and execute events in the open like MozFest does. I guess this would also tie into the larger framework that @Saallen was mentioning before.

**Comment by sabrinang** [comment]
@Saallen Please provide approved google doc link with final copy

**Comment by marcwalsh** [comment]
This is the copy I completed with @Saallen yesterday:
https://docs.google.com/document/d/1Ot95Gh-gLuHlLz4NYkH5Yf6CZmdweTLntE_LBj5q1fQ/edit?usp=sharing

Sarah can you approve please? 

- [ ]

**Comment by Saallen** [comment]
Approved- 
please amend and update @mmmavis

**Comment by sabrinang** [comment]
Closing copy issue and work will continue on implementation ticket #950
