### ISSUE TITLE
New question on Call for Proposals form

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozillafestival.org#952]
**Question** - From which country are you from?
**Subtext**  - We ask this question in order to get a better understanding of who is participating in MozFest. You can respond as a resident or as a citizen of a country. It will not be linked to your submission on Github
**Reponse action**- choose from a drop down menu

**Curation piece**- the response does not show up on Github but wranglers should measure against this list before they choose their final sessions to ensure georgraphical spread

@amirad - let us know what you think about this question

**Comment by amirad** [comment]
Do you want to know where people live? If so I would say: What country do you currently reside in? 
If you want to know where people are from, I would say: Which country are you from?

I would go with the "where people live" so that it's easy to answer (as opposed to the second which can be a multitude of answers) and more direct for the proposal process. 

I would also add to that subtext area "It will not be linked to your submission on Github, for privacy reasons and will only be shared with Mozilla staff and Mozfest wranglers."

**Comment by Saallen** [comment]
Confirming new question for Call for Proposals @mmmavis and ready for you to add to the call form

Question - What country do you currently reside in?
Subtext - We ask this question in order to get a better understanding of who is participating in MozFest. You can respond as a resident or as a citizen of a country. It will not be linked to your submission on Github for privacy reasons and will only be shared with Mozilla staff and Mozfest wranglers.
Reponse action- choose from a drop down menu

**Comment by mmmavis** [comment]
@Saallen where in the form should we add this question? Somewhere in the "Your information" section? https://mozillafestival.org/proposals

**Comment by Saallen** [comment]
@mmmavis add it under organisation question.
It should be mandatory

**Comment by mmmavis** [comment]
Hey @Saallen @amirad should we also include a "I prefer not to specify" option in the country dropdown list in case someone doesn't feel comfortable leaving that info? If so, what text should we use?

**Comment by Saallen** [comment]
Hey- I think that is a great idea.
Please use the text you have outlined above
I prefer not to specify

**Comment by amirad** [comment]
WFM!

**Comment by mmmavis** [comment]
okie dokie

**Comment by mmmavis** [comment]
Done!
